# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: VS build tests

on:
  push:
    branches: [master, feature/**, bugfix/**]
    paths-ignore: ['docs/**', '*.md']
  pull_request:
    branches: [master]
    paths-ignore: ['docs/**', '*.md']

jobs:
  framework-regression:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [2.7, 3.8]
  
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Run VS building tests
      run: |
        Start-Process "cmd.exe"  "/c test_vs_build.cmd"
